parameters:
    oxpus.dlext.tables.dl_auth: '%core.table_prefix%dl_auth'
    oxpus.dlext.tables.dl_tracker: '%core.table_prefix%dl_bug_tracker'
    oxpus.dlext.tables.dl_bug_history: '%core.table_prefix%dl_bug_history'
    oxpus.dlext.tables.dl_cat: '%core.table_prefix%downloads_cat'
    oxpus.dlext.tables.dl_cat_traf: '%core.table_prefix%dl_cat_traf'
    oxpus.dlext.tables.dl_comments: '%core.table_prefix%dl_comments'
    oxpus.dlext.tables.dl_ext_blacklist: '%core.table_prefix%dl_ext_blacklist'
    oxpus.dlext.tables.dl_favorites: '%core.table_prefix%dl_favorites'
    oxpus.dlext.tables.dl_fields: '%core.table_prefix%dl_fields'
    oxpus.dlext.tables.dl_fields_data: '%core.table_prefix%dl_fields_data'
    oxpus.dlext.tables.dl_fields_lang: '%core.table_prefix%dl_fields_lang'
    oxpus.dlext.tables.dl_hotlink: '%core.table_prefix%dl_hotlink'
    oxpus.dlext.tables.dl_images: '%core.table_prefix%dl_images'
    oxpus.dlext.tables.dl_lang: '%core.table_prefix%dl_lang'
    oxpus.dlext.tables.dl_notraf: '%core.table_prefix%dl_notraf'
    oxpus.dlext.tables.dl_ratings: '%core.table_prefix%dl_ratings'
    oxpus.dlext.tables.dl_reports: '%core.table_prefix%dl_reports'
    oxpus.dlext.tables.dl_stats: '%core.table_prefix%dl_stats'
    oxpus.dlext.tables.dl_versions: '%core.table_prefix%dl_versions'
    oxpus.dlext.tables.dl_ver_files: '%core.table_prefix%dl_ver_files'
    oxpus.dlext.tables.downloads: '%core.table_prefix%downloads'
